name: Workflow concurrency

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency: 
     group: deploy
     cancel-in-progress: true

     steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.2
      - name: install dep
        run: npm install
      - name: build
        run: npm run build
      - name: deploy app
        run: echo "jinkla na"

      
      
