name: Workflow concurrency

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Deploy app
        run: echo "jinkla na rao"
