name: Build my angular app

on: 
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build angular app
        run: npm run build
