name: Raut workflow

on:
  schedule:
    - cron: "8 15 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello from scheduled workflow by shubham raut"
